<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Sortie;

/**
 * ParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $idSortie
     * @return array
     */
    public function getParticipantsBySorties($idSortie){

        $em = $this->getEntityManager('s');
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('s')
            ->from(Sortie::class, 's')
            ->innerJoin("s.participants", "p", "WITH", "p.id = :idSortie")
            ->setParameter("idSortie", $idSortie);

        return $queryBuilder->getQuery()->getResult();
    }


}
