<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Participant;
use AppBundle\Entity\Sortie;

/**
 * SortieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SortieRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $user
     * @return array
     */
    public function getSortiesByAuthor($user)
    {

        $em = $this->getEntityManager('s');
        $queryBuilder = $em->createQueryBuilder();
        $queryBuilder->select('s')
            ->from(Sortie::class, 's')
            ->innerJoin("s.organisateur", "p", "WITH")
            ->where("p = :id")
            ->setParameter("id", $user->getId());

        return $queryBuilder->getQuery()->getResult();
    }

    public function getSortiesByRegistering($user)
    {

        $em = $this->getEntityManager('s');
        $queryBuilder = $em->createQueryBuilder();

        $queryBuilder->select ('s')
            ->from(Sortie::class, 's')
            ->innerJoin('s.participants',"p")
            ->where('p.id = :id')
            ->setParameter("id", $user);

        dump($queryBuilder->getDQL());

        return $queryBuilder->getQuery()->getResult();
    }

    public function getSortiesByNotRegistered($user)
    {

        $em = $this->getEntityManager('s');
        $queryBuilder = $em->createQueryBuilder();

        $queryBuilder->select ('s')
            ->from(Sortie::class, 's')
            ->innerJoin('s.participants',"p");
//            ->where('p.id = :id')
//            ->setParameter("id", $user);

        dump($queryBuilder->getDQL());

        return $queryBuilder->getQuery()->getResult();
    }
}
