# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        AppBundle\Entity\Participant:
            algorithm: sha256

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        db_providers:
            entity:
                class: AppBundle:Participant
                property: username

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            anonymous: true
            provider: db_providers

            form_login:
                login_path: /login
                check_path: /login

            logout:
                path: logout
                target: /
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        #- { path: ^/admin, roles: ROLE_ADMIN }
        #- { path: ^/, roles: ROLE_USER }